App\Core\Domain\Entity\Channel:
  attributes:
    id:
      groups: ['channel', 'message', 'server']
    name:
      groups: ['channel', 'server']
    type:
      groups: ['channel', 'server']
    messages:
      groups: ['channel']