App\Core\Domain\Entity\Channel:
  attributes:
    id:
      groups: ['channel', 'message']
    name:
      groups: ['channel']
    type:
      groups: ['channel']
    messages:
      groups: ['channel']