App\Core\Domain\Entity\Server:
  attributes:
    id:
      groups: ['server', 'profile-server']
    name:
      groups: ['server', 'profile-server']
    owner:
      groups: ['server', 'profile-server']
    channels:
      groups: ['server']
    settings:
      groups: ['profile-server']